#!/usr/bin/env bash
# Shared utilities for sandbox tasks. Source this file, don't execute it.

sandbox_dir() {
    local base="${DAFT_SANDBOX_BASE:-/tmp}"
    local worktree_path
    # pwd returns the project root because mise always runs tasks from there
    worktree_path="$(pwd)"

    local hash
    if command -v sha256sum &>/dev/null; then
        hash=$(echo -n "$worktree_path" | sha256sum | cut -c1-8)
    else
        hash=$(echo -n "$worktree_path" | shasum -a 256 | cut -c1-8)
    fi

    echo "${base}/daft-sandbox-${hash}"
}

# Re-point daft at the per-worktree sandbox config/data/state.
#
# Sandbox tasks run via `mise run sandbox:<task>`; mise loads its env from
# `mise.toml` -> `_.source = ["shared-env.sh"]`, which exports
# `DAFT_CONFIG_DIR=<git-common-dir>/.daft-sandbox`. That value belongs to the
# *project*, not to the per-worktree sandbox in $(sandbox_dir). Without this
# re-point, `daft repo remove` invoked from inside a sandbox task would
# operate on the project's trust DB — leaving stale entries in the sandbox's
# `repos.json` and silently bypassing per-repo hook trust. The runtime
# sandbox shell (.envrc generated by `sandbox/_default`) sets these three the
# same way; this helper keeps mise-task daft invocations consistent with it.
sandbox_use_isolated_daft_env() {
    local sb
    sb="$(sandbox_dir)"
    export DAFT_CONFIG_DIR="${sb}/config"
    export DAFT_DATA_DIR="${sb}/data"
    export DAFT_STATE_DIR="${sb}/state"
}
