//! Rail-native renderer for hook jobs (#651), at two densities.
//!
//! Succinct (default): one receipt row per job in the rail's own grammar,
//! tucked into the rail gutter (`│  ✓  <job>`) under a `├─ <section>` anchor
//! — no banner, no output dumps, no summary. Live, each running job is a
//! spinner bar whose annotation is the job's latest output line, dim,
//! updating in place. A failed job's captured output rides
//! [`TimelineHandle::defer_after_footer`] and lands below the rail footer,
//! where the rail already puts failure detail.
//!
//! Verbose (`-v` / `daft.hooks.output.verbose`): the same rows, plus each
//! job's log hanging from its glyph column on an inner thread
//! (`│  │    <line>`). The thread opens with the `❯ <command>` provenance
//! line, shows a rolling window of `tailLines` lines while the job runs, and
//! persists the full log into the receipt when it resolves — grey under a
//! success (a receipt), default ink under a failure (evidence). The anchor
//! carries the hook key + engine version as a grey annotation, and the
//! section closes with a `└ all jobs in <t>` note. With the log inline, a
//! failure defers only the runner's one-line exit fact after the footer —
//! never a dump repeat.

use super::render::{self, HookJobFace};
use super::{HookEmbed, TimelineHandle};
use crate::output::hook_progress::{JobOutcome, JobResultEntry, format_duration};
use crate::output::palette::{DARK_GREY, GREY};
use crate::settings::HookOutputConfig;
use crate::styles;
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

/// A per-job skip reason generated by the condition machinery (`skip:` /
/// `only:` in the job's YAML). The config working as designed is not receipt
/// material — these resolve silently, like the carry row on a clean tree.
/// Everything else that reaches a skip (`--skip-hooks` exclusions,
/// dependency failures) renders the yellow attention row.
///
/// Defensive on the per-job path: today condition skips never reach the
/// presenter at all (`yaml_jobs_to_specs` filters them before execution and
/// only the job store records them); this guards the succinct rail if that
/// ever changes. Load-bearing on the hook level: `resolve_hook_step` uses it
/// to vanish a whole phase skipped by `hook_def.skip`/`only`.
pub(super) fn is_condition_skip(reason: &str) -> bool {
    reason.starts_with("skip: ") || reason.starts_with("only: ")
}

/// One-line rendering of a job's command for the `❯` provenance line:
/// block-scalar `run:` commands carry embedded newlines that would tear the
/// thread apart (a println line must stay a line), so everything past the
/// first non-empty line collapses into `…`.
fn command_line(cmd: &str) -> String {
    let mut lines = cmd.lines().filter(|l| !l.trim().is_empty());
    let first = lines.next().unwrap_or("").trim_end();
    match lines.next() {
        Some(_) => format!("{first} \u{2026}"),
        None => first.to_string(),
    }
}

struct JobState {
    bar: ProgressBar,
    /// The `❯ <command>` provenance thread bar (verbose, preview known).
    cmd_bar: Option<ProgressBar>,
    /// Rolling live-tail thread bars (verbose; capped at `tail_lines`).
    tail_bars: Vec<ProgressBar>,
    /// Blank spacer bar at the bottom of the job's live block (verbose) so
    /// parallel blocks don't fuse — the live twin of the receipt's trailing
    /// spacer line.
    trailer: Option<ProgressBar>,
    /// Everything the job printed, buffered for the receipt log (verbose)
    /// or the deferred failure dump (succinct).
    output: Vec<String>,
    /// The live annotation: latest output line, seeded from the job's
    /// description. Kept unpainted; painted at composition.
    annotation: Option<String>,
    /// The command preview, kept for the receipt log's `❯` line.
    command_preview: Option<String>,
    /// Set on the first displayed output line; the promoter ticker exits
    /// once it's up (output un-promotes).
    output_seen: Arc<AtomicBool>,
    /// Set when the job's bars leave the region; stops a pending promoter.
    resolved: Arc<AtomicBool>,
    /// Whether the elapsed counter currently occupies the annotation slot —
    /// set by the promoter ticker, cleared when output arrives.
    promoted: Arc<AtomicBool>,
}

pub struct RailHookRenderer {
    mp: MultiProgress,
    anchor: ProgressBar,
    handle: TimelineHandle,
    use_color: bool,
    quiet: bool,
    /// `-v` / `daft.hooks.output.verbose`: thread each job's log under its
    /// row instead of the succinct latest-line annotation.
    verbose: bool,
    /// Live-thread window size (`tailLines`); the receipt is never windowed.
    tail_lines: usize,
    /// `timerDelay` before a silent job's spinner gains an elapsed suffix.
    timer_delay: Duration,
    section_label: Option<String>,
    job_style: ProgressStyle,
    /// Static thread-bar template: `│  │    {wide_msg}` (inner `│` a tier
    /// below the rail).
    thread_style: ProgressStyle,
    /// The live block's bottom spacer (an empty thread line `│  │`).
    trailer_style: ProgressStyle,
    jobs: HashMap<String, JobState>,
    /// Jobs already resolved `✗` — used to intercept the runner's redundant
    /// `Job '<name>' failed…` message (the row carries the fact; verbose
    /// defers the line's exit code after the footer).
    failed: HashSet<String>,
    finished: Vec<JobResultEntry>,
    /// Running max of started job names; live bars re-pad when it grows.
    name_width: usize,
}

impl RailHookRenderer {
    pub fn new(embed: HookEmbed, handle: TimelineHandle, config: &HookOutputConfig) -> Self {
        // `wide_msg`, not `msg`: hook output is arbitrary — a line wider
        // than the terminal must truncate, or it wraps and desyncs
        // indicatif's line accounting. The rail gutter rides the template —
        // the spinner glyph lives there, so the message can't provide it.
        let base = if embed.use_color {
            "{spinner:.cyan}  {wide_msg}"
        } else {
            "{spinner}  {wide_msg}"
        };
        let job_style = ProgressStyle::with_template(&render::gutter(base, embed.use_color))
            .expect("job template is valid")
            .tick_chars(super::region::TICK_CHARS);
        let inner = render::paint(DARK_GREY, "\u{2502}", embed.use_color);
        let thread_style = ProgressStyle::with_template(&render::gutter(
            &format!("{inner}    {{wide_msg}}"),
            embed.use_color,
        ))
        .expect("thread template is valid");
        // The live trailer renders the thread's empty closing line. `{msg}`
        // + a set_message at creation (the `add_line_bar` pattern): a bar
        // that never receives a state poke never draws.
        let trailer_style =
            ProgressStyle::with_template("{msg}").expect("trailer template is valid");
        Self {
            mp: embed.mp,
            anchor: embed.anchor,
            handle,
            use_color: embed.use_color,
            quiet: config.quiet,
            verbose: config.verbose,
            tail_lines: config.tail_lines as usize,
            timer_delay: Duration::from_secs(u64::from(config.timer_delay_secs)),
            section_label: embed.section_label,
            job_style,
            thread_style,
            trailer_style,
            jobs: HashMap::new(),
            failed: HashSet::new(),
            finished: Vec::new(),
            name_width: 0,
        }
    }

    /// The `├─ <section>` anchor. The consumed rail row's label names the
    /// section; gate embeds (pre-push under an active Push row) fall back to
    /// the phase name. Verbose carries the banner's surviving facts — the
    /// raw hook key (the daft.yml lookup key) and the engine version — as a
    /// grey annotation; the `on: <target>` segment is gone for good, because
    /// the rail header or branch anchor already names the target.
    pub fn print_header(&self, hook_name: &str, _target: Option<&str>) {
        let label = match &self.section_label {
            Some(label) => label.clone(),
            None => format!("{hook_name} hooks"),
        };
        let annotation = self
            .verbose
            .then(|| format!("{hook_name} \u{b7} daft v{}", crate::VERSION));
        self.mp
            .println(render::group(&label, annotation.as_deref(), self.use_color))
            .ok();
    }

    pub fn start_job(&mut self, name: &str, command_preview: Option<&str>) {
        self.start_job_with_description(name, None, command_preview);
    }

    pub fn start_job_with_description(
        &mut self,
        name: &str,
        description: Option<&str>,
        command_preview: Option<&str>,
    ) {
        let bar = self
            .mp
            .insert_before(&self.anchor, ProgressBar::new_spinner());
        bar.set_style(self.job_style.clone());

        // Verbose: open the job's thread with the `❯ <command>` provenance
        // line (quiet keeps its "suppress hook output" contract — threads
        // vanish entirely).
        let cmd_bar = if self.verbose && !self.quiet {
            command_preview.map(|cmd| {
                let pb = self.mp.insert_after(&bar, ProgressBar::new_spinner());
                pb.set_style(self.thread_style.clone());
                pb.set_message(render::paint(
                    DARK_GREY,
                    &format!("\u{276f} {}", command_line(cmd)),
                    self.use_color,
                ));
                pb
            })
        } else {
            None
        };

        // The block's bottom air, so parallel live blocks don't fuse. Sits
        // below the cmd bar; tails insert above it (`insert_after` the last
        // tail / cmd / job bar places them before this one).
        let trailer = if self.verbose && !self.quiet {
            let anchor = cmd_bar.as_ref().unwrap_or(&bar);
            let pb = self.mp.insert_after(anchor, ProgressBar::new_spinner());
            pb.set_style(self.trailer_style.clone());
            pb.set_message(self.thread_air());
            Some(pb)
        } else {
            None
        };

        let state = JobState {
            bar,
            cmd_bar,
            tail_bars: Vec::new(),
            trailer,
            output: Vec::new(),
            annotation: description.map(str::to_string),
            command_preview: command_preview.map(str::to_string),
            output_seen: Arc::new(AtomicBool::new(false)),
            resolved: Arc::new(AtomicBool::new(false)),
            promoted: Arc::new(AtomicBool::new(false)),
        };
        self.jobs.insert(name.to_string(), state);
        self.grow_width_to(name.chars().count());
        self.refresh_bar(name);
        if let Some(state) = self.jobs.get(name) {
            state.bar.enable_steady_tick(Duration::from_millis(80));
            if self.verbose {
                // Ticking promoter: a job still silent past `timerDelay`
                // shows a dim elapsed counter in its annotation slot,
                // refreshed once a second, until output or resolution.
                // Wall-clock driven (the old block's lesson: long silent
                // jobs never trigger output-driven swaps). The message
                // always travels the `{wide_msg}` template — a
                // template-side `{elapsed}` would need `{msg}`, and
                // unbounded content in `{msg}` wraps and desyncs
                // indicatif's line accounting (a paragraph-long job
                // description is unbounded content).
                let bar = state.bar.clone();
                let seen = Arc::clone(&state.output_seen);
                let done = Arc::clone(&state.resolved);
                let flag = Arc::clone(&state.promoted);
                let delay = self.timer_delay;
                let use_color = self.use_color;
                let width = self.name_width;
                let name = name.to_string();
                let started = std::time::Instant::now();
                std::thread::spawn(move || {
                    std::thread::sleep(delay);
                    // The message to fall back to if an iteration races a
                    // just-arrived first output line: the composition as of
                    // promotion time (name + description annotation).
                    let resting = bar.message();
                    loop {
                        if done.load(Ordering::SeqCst) || seen.load(Ordering::SeqCst) {
                            flag.store(false, Ordering::SeqCst);
                            break;
                        }
                        flag.store(true, Ordering::SeqCst);
                        let elapsed = render::paint(
                            GREY,
                            &format!("({})", format_duration(started.elapsed())),
                            use_color,
                        );
                        bar.set_message(format!("{name:<width$}  {elapsed}"));
                        // Re-check after writing: if output landed in the
                        // gap, this write clobbered a fresher message and
                        // nothing else will repaint a silent-again bar —
                        // put the resting composition back.
                        if done.load(Ordering::SeqCst) || seen.load(Ordering::SeqCst) {
                            flag.store(false, Ordering::SeqCst);
                            bar.set_message(resting);
                            break;
                        }
                        std::thread::sleep(Duration::from_secs(1));
                    }
                });
            }
        }
    }

    pub fn update_job_output(&mut self, name: &str, line: &str) {
        let Some(state) = self.jobs.get_mut(name) else {
            return;
        };
        state.output.push(line.to_string());
        if self.quiet {
            return;
        }
        if self.verbose {
            // The thread carries the liveness — the annotation slot keeps
            // the job's description instead of racing the newest tail line.
            // Output un-promotes: the elapsed counter answers "is this
            // silent job alive?", and output answers it better. Checked on
            // every line (not just the first) so a promoter racing past the
            // first line still loses on the next one; the ticker itself
            // exits on its next wake.
            state.output_seen.store(true, Ordering::SeqCst);
            let unpromoted = state.promoted.swap(false, Ordering::SeqCst);
            // Grow the thread one bar per line until the window is full…
            if state.tail_bars.len() < self.tail_lines {
                let anchor = state
                    .tail_bars
                    .last()
                    .or(state.cmd_bar.as_ref())
                    .unwrap_or(&state.bar);
                let pb = self.mp.insert_after(anchor, ProgressBar::new_spinner());
                pb.set_style(self.thread_style.clone());
                state.tail_bars.push(pb);
            }
            // …then roll the buffer's tail through it.
            let start = state.output.len().saturating_sub(state.tail_bars.len());
            for (i, pb) in state.tail_bars.iter().enumerate() {
                let text = state.output.get(start + i).map_or("", String::as_str);
                pb.set_message(render::paint(GREY, text, self.use_color));
            }
            if unpromoted {
                // Put the description annotation back in place of the
                // elapsed counter.
                self.refresh_bar(name);
            }
        } else {
            // Succinct's single line of liveness: the latest output line
            // rides the annotation slot.
            state.annotation = Some(line.trim_end().to_string());
            self.refresh_bar(name);
        }
    }

    pub fn finish_job_success(&mut self, name: &str, duration: Duration) {
        let state = self.remove_bar(name);
        self.persist_receipt(render::hook_job_row(
            &HookJobFace::Done {
                duration: Some(duration),
            },
            name,
            None,
            self.name_width,
            self.use_color,
        ));
        self.persist_log(state.as_ref(), false);
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Success,
            duration,
        });
    }

    pub fn finish_job_failure(&mut self, name: &str, duration: Duration) {
        let state = self.remove_bar(name);
        self.persist_receipt(render::hook_job_row(
            &HookJobFace::Failed,
            name,
            self.duration_annotation(duration).as_deref(),
            self.name_width,
            self.use_color,
        ));
        self.failed.insert(name.to_string());
        self.persist_log(state.as_ref(), true);
        // Succinct: the captured output lands below the rail footer — the
        // rail's errors-after pattern — not torn through the live bars.
        // Verbose already printed the log inline, so nothing defers here
        // (the runner's exit-fact line defers via `println` instead).
        // `quiet` keeps its "suppress hook stdout/stderr" contract.
        let output = state.map(|s| s.output).unwrap_or_default();
        if !self.verbose && !self.quiet && !output.is_empty() {
            let head = if self.use_color {
                format!(
                    "{}error:{} hook job '{name}' failed:",
                    styles::RED,
                    styles::RESET
                )
            } else {
                format!("error: hook job '{name}' failed:")
            };
            let mut lines = vec![head];
            lines.extend(output.iter().map(|l| format!("  {l}")));
            self.handle.defer_after_footer(lines);
        }
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Failed,
            duration,
        });
    }

    pub fn finish_job_skipped(
        &mut self,
        name: &str,
        reason: &str,
        duration: Duration,
        show_duration: bool,
        _command_preview: Option<&str>,
    ) {
        self.remove_bar(name);
        if !is_condition_skip(reason) {
            self.persist_receipt(render::hook_job_row(
                &HookJobFace::SkippedAttention,
                name,
                Some(&format!("skipped \u{2014} {reason}")),
                self.name_width,
                self.use_color,
            ));
        }
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Skipped {
                reason: reason.to_string(),
                show_duration,
            },
            duration,
        });
    }

    /// Hooks have no cancellation path today (only `daft exec` cancels, and
    /// it always runs the block renderer) — defensive parity. Verbose
    /// treats the log as evidence, same as a failure.
    pub fn finish_job_cancelled(&mut self, name: &str, duration: Duration) {
        let state = self.remove_bar(name);
        self.persist_receipt(render::hook_job_row(
            &HookJobFace::Failed,
            name,
            Some("cancelled"),
            self.name_width,
            self.use_color,
        ));
        self.failed.insert(name.to_string());
        self.persist_log(state.as_ref(), true);
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Failed,
            duration,
        });
    }

    /// `↻ <name>  background` — the dispatch receipt; the job itself runs
    /// under the coordinator, visible via `daft hooks jobs`.
    pub fn show_background_job(&mut self, name: &str, _description: Option<&str>) {
        self.grow_width_to(name.chars().count());
        self.persist_receipt(render::hook_job_row(
            &HookJobFace::Background,
            name,
            None,
            self.name_width,
            self.use_color,
        ));
    }

    pub fn push_finished_job(&mut self, entry: JobResultEntry) {
        self.finished.push(entry);
    }

    /// Succinct: no summary — every job already has exactly one receipt
    /// row. Verbose: the legacy summary's one surviving fact, the phase
    /// total, closes the section as a recessed `└` note — the section's own
    /// rail end (always with the total; the 1s threshold is for row
    /// durations, not the relocated "done in").
    pub fn print_summary(&self, total_duration: Duration) {
        if !self.verbose || self.finished.is_empty() {
            return;
        }
        let note = render::section_close(
            &format!("all jobs in {}", format_duration(total_duration)),
            self.use_color,
        );
        self.mp.println(render::gutter(&note, self.use_color)).ok();
    }

    pub fn take_finished_jobs(&mut self) -> Vec<JobResultEntry> {
        std::mem::take(&mut self.finished)
    }

    pub fn println(&self, msg: &str) {
        // The runner follows every on_job_failure with a
        // `Job '<name>' failed…` message (runner::report_completion) — on
        // the rail that is redundant with the `✗` row. Succinct drops it
        // (the deferred dump carries the fact); verbose — whose log is
        // already inline — recasts it as the one post-footer error fact,
        // keeping the exit code: `Job 'x' failed (exit code: 1)` becomes
        // `error: hook job 'x' failed (exit code: 1)`. Author-supplied
        // `fail_text` and other messages (e.g. the `⟳ N background jobs
        // running` notice) pass through as section content, each line
        // tucked into the gutter.
        let redundant = self
            .failed
            .iter()
            .any(|name| msg.starts_with(&format!("Job '{name}' failed")));
        if redundant {
            if self.verbose {
                let suffix = msg.strip_prefix("Job ").unwrap_or(msg);
                let line = if self.use_color {
                    format!("{}error:{} hook job {suffix}", styles::RED, styles::RESET)
                } else {
                    format!("error: hook job {suffix}")
                };
                self.handle.defer_after_footer(vec![line]);
            }
            return;
        }
        for line in msg.lines() {
            // Notice tier: recessed like notes, not competing with the
            // section's own receipt rows.
            let line = render::paint(GREY, line, self.use_color);
            self.mp.println(render::gutter(&line, self.use_color)).ok();
        }
    }

    /// Persist a receipt row inside the rail gutter — every job row is
    /// section content under the `├─` anchor.
    fn persist_receipt(&self, row: String) {
        self.mp.println(render::gutter(&row, self.use_color)).ok();
    }

    /// Verbose receipt log: the job's full thread, persisted under its row,
    /// closed with one empty thread line so consecutive blocks don't fuse.
    /// Quiet suppresses the whole thread.
    fn persist_log(&self, state: Option<&JobState>, failed: bool) {
        if !self.verbose || self.quiet {
            return;
        }
        let Some(state) = state else {
            return;
        };
        for line in self.compose_log(state, failed) {
            self.mp.println(line).ok();
        }
        self.mp.println(self.thread_air()).ok();
    }

    /// The thread's empty closing line: `│  │` — the air stays inside the
    /// section (the job's own thread), never spending the rail's lone-`│`
    /// section-boundary glyph on intra-section spacing.
    fn thread_air(&self) -> String {
        let inner = render::paint(DARK_GREY, "\u{2502}", self.use_color);
        render::gutter(&inner, self.use_color)
    }

    /// The receipt log's lines. `❯ <command>` provenance and the
    /// `(no output)` marker sit on the metadata tier (dark grey); output
    /// recedes to the scaffolding grey under a success (a receipt) and
    /// keeps the default ink under a failure (evidence).
    fn compose_log(&self, state: &JobState, failed: bool) -> Vec<String> {
        let mut lines = Vec::new();
        if let Some(cmd) = &state.command_preview {
            lines.push(self.thread_line(render::paint(
                DARK_GREY,
                &format!("\u{276f} {}", command_line(cmd)),
                self.use_color,
            )));
        }
        if state.output.is_empty() {
            lines.push(self.thread_line(render::paint(DARK_GREY, "(no output)", self.use_color)));
        } else {
            for line in &state.output {
                let text = if failed {
                    line.clone()
                } else {
                    render::paint(GREY, line, self.use_color)
                };
                lines.push(self.thread_line(text));
            }
        }
        lines
    }

    /// One thread line: `│  │    <text>` — the inner `│` hangs from the job
    /// row's glyph column, a tier below the rail.
    fn thread_line(&self, text: String) -> String {
        let inner = render::paint(DARK_GREY, "\u{2502}", self.use_color);
        render::gutter(&format!("{inner}    {text}"), self.use_color)
    }

    /// Test-only: whether the job's elapsed suffix is currently promoted.
    #[cfg(test)]
    fn timer_promoted(&self, name: &str) -> bool {
        self.jobs
            .get(name)
            .map(|s| s.promoted.load(Ordering::SeqCst))
            .unwrap_or(false)
    }

    /// Bump the alignment column and re-pad every live bar when it grows.
    fn grow_width_to(&mut self, width: usize) {
        if width <= self.name_width {
            return;
        }
        self.name_width = width;
        let names: Vec<String> = self.jobs.keys().cloned().collect();
        for name in names {
            self.refresh_bar(&name);
        }
    }

    /// Recompose a live bar's message from its stored annotation.
    fn refresh_bar(&self, name: &str) {
        let Some(state) = self.jobs.get(name) else {
            return;
        };
        let msg = match state.annotation.as_deref().filter(|a| !a.is_empty()) {
            Some(a) => format!(
                "{name:<width$}  {}",
                render::paint(DARK_GREY, a, self.use_color),
                width = self.name_width
            ),
            None => name.to_string(),
        };
        state.bar.set_message(msg);
    }

    /// Remove the job's live bars — the spinner and its whole thread
    /// (receipts replace them via `mp.println` — the atomic swap; never
    /// `finish_and_clear`, per the zombie-line lesson). Returns the state
    /// for the receipt log. Jobs that never started (skips) have no state;
    /// that's fine.
    fn remove_bar(&mut self, name: &str) -> Option<JobState> {
        let state = self.jobs.remove(name)?;
        state.resolved.store(true, Ordering::SeqCst);
        state.bar.disable_steady_tick();
        self.mp.remove(&state.bar);
        if let Some(pb) = &state.cmd_bar {
            self.mp.remove(pb);
        }
        for pb in &state.tail_bars {
            self.mp.remove(pb);
        }
        if let Some(pb) = &state.trailer {
            self.mp.remove(pb);
        }
        Some(state)
    }

    /// The rail's duration vocabulary for faces that don't carry their own:
    /// dim, parenthesized, only at ≥ 1s.
    fn duration_annotation(&self, duration: Duration) -> Option<String> {
        (duration >= render::DURATION_THRESHOLD).then(|| {
            render::paint(
                GREY,
                &format!(
                    "({})",
                    crate::output::hook_progress::format_duration(duration)
                ),
                self.use_color,
            )
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::timeline::{Timeline, TimelineMode};
    use indicatif::{InMemoryTerm, ProgressDrawTarget};

    fn harness_with(
        config: HookOutputConfig,
        section_label: Option<&str>,
        use_color: bool,
    ) -> (RailHookRenderer, InMemoryTerm, TimelineHandle) {
        let term = InMemoryTerm::new(40, 120);
        let mp =
            MultiProgress::with_draw_target(ProgressDrawTarget::term_like(Box::new(term.clone())));
        let anchor = mp.add(ProgressBar::new_spinner());
        anchor.set_style(ProgressStyle::with_template("{msg}").unwrap());
        let tl = Timeline::new(TimelineMode::Interactive { color: false }, false, "t");
        let handle = tl.handle();
        let embed = HookEmbed {
            mp,
            anchor,
            use_color,
            section_label: section_label.map(String::from),
        };
        (
            RailHookRenderer::new(embed, handle.clone(), &config),
            term,
            handle,
        )
    }

    fn harness(
        section_label: Option<&str>,
        quiet: bool,
    ) -> (RailHookRenderer, InMemoryTerm, TimelineHandle) {
        harness_with(
            HookOutputConfig {
                quiet,
                ..Default::default()
            },
            section_label,
            false,
        )
    }

    fn verbose_config() -> HookOutputConfig {
        HookOutputConfig {
            verbose: true,
            ..Default::default()
        }
    }

    fn deferred(handle: &TimelineHandle) -> Vec<String> {
        handle.inner.lock().unwrap().deferred_after_footer.clone()
    }

    #[test]
    fn success_receipt_uses_rail_grammar() {
        let (mut r, term, _h) = harness(Some("post-create hooks"), false);
        r.print_header("worktree-post-create", Some("feat/x"));
        r.start_job_with_description("build", None, Some("cargo build"));
        r.update_job_output("build", "compiling…");
        r.finish_job_success("build", Duration::from_millis(2100));
        assert_eq!(
            term.contents(),
            "\u{251c}\u{2500} post-create hooks\n\u{2502}  \u{2713}  build  (2.1s)"
        );
        let jobs = r.take_finished_jobs();
        assert_eq!(jobs.len(), 1);
        assert!(matches!(jobs[0].outcome, JobOutcome::Success));
    }

    #[test]
    fn subsecond_success_hides_duration() {
        let (mut r, term, _h) = harness(None, false);
        r.start_job("fmt", None);
        r.finish_job_success("fmt", Duration::from_millis(300));
        assert_eq!(term.contents(), "\u{2502}  \u{2713}  fmt");
    }

    #[test]
    fn gate_embed_derives_anchor_from_phase_name() {
        let (r, term, _h) = harness(None, false);
        r.print_header("pre-push", Some("feat/x"));
        assert_eq!(term.contents(), "\u{251c}\u{2500} pre-push hooks");
    }

    #[test]
    fn failure_row_and_dump_deferred_after_footer() {
        let (mut r, term, h) = harness(None, false);
        r.start_job("build", None);
        r.update_job_output("build", "error: lockfile out of date");
        r.update_job_output("build", "note: run bun install");
        r.finish_job_failure("build", Duration::from_millis(2900));
        assert_eq!(term.contents(), "\u{2502}  \u{2717}  build  (2.9s)");
        assert_eq!(
            deferred(&h),
            vec![
                "error: hook job 'build' failed:".to_string(),
                "  error: lockfile out of date".to_string(),
                "  note: run bun install".to_string(),
            ]
        );
    }

    #[test]
    fn failure_without_output_defers_nothing() {
        let (mut r, _term, h) = harness(None, false);
        r.start_job("build", None);
        r.finish_job_failure("build", Duration::from_secs(1));
        assert!(deferred(&h).is_empty());
    }

    #[test]
    fn quiet_suppresses_annotation_and_dump() {
        let (mut r, term, h) = harness(None, true);
        r.start_job("build", None);
        r.update_job_output("build", "secret output");
        assert!(
            !term.contents().contains("secret output"),
            "quiet must keep hook output off the live bar: {}",
            term.contents()
        );
        r.finish_job_failure("build", Duration::from_secs(2));
        assert!(deferred(&h).is_empty(), "quiet suppresses the dump");
    }

    #[test]
    fn requested_and_dependency_skips_render_yellow() {
        // Pins every reason the executor can send through on_job_skipped:
        // SkipCause::reason() (job_adapter) and the runner's dep-failure
        // family. All are attention-worthy on the rail.
        let reasons = [
            "requested (--skip-hooks)",
            "depends on install (skipped)",
            "dependency failed",
            "previous job failed",
            "foreground dependency failed",
        ];
        for reason in reasons {
            let (mut r, term, _h) = harness(None, false);
            r.finish_job_skipped("lint", reason, Duration::ZERO, false, None);
            assert_eq!(
                term.contents(),
                format!("\u{2502}  \u{2193}  lint  skipped \u{2014} {reason}"),
                "reason {reason:?} must render the attention row"
            );
        }
    }

    #[test]
    fn condition_skips_resolve_silently() {
        // Defensive: condition skips are filtered before the presenter
        // today; if they ever arrive, the config working as designed must
        // not become receipt noise.
        for reason in ["skip: true", "only: env $CI is not set"] {
            let (mut r, term, _h) = harness(None, false);
            r.finish_job_skipped("lint", reason, Duration::ZERO, false, None);
            assert_eq!(term.contents(), "", "reason {reason:?} must be silent");
            let jobs = r.take_finished_jobs();
            assert!(
                matches!(&jobs[0].outcome, JobOutcome::Skipped { .. }),
                "silent skips still record their outcome"
            );
        }
    }

    #[test]
    fn background_row_persists_with_fixed_annotation() {
        let (mut r, term, _h) = harness(None, false);
        r.show_background_job("check-todos", Some("scan for TODOs"));
        r.push_finished_job(JobResultEntry {
            name: "check-todos".to_string(),
            outcome: JobOutcome::Background { description: None },
            duration: Duration::ZERO,
        });
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{21bb}  check-todos  background"
        );
        assert!(matches!(
            r.take_finished_jobs()[0].outcome,
            JobOutcome::Background { .. }
        ));
    }

    #[test]
    fn runner_failure_message_is_suppressed_for_failed_jobs() {
        let (mut r, term, _h) = harness(None, false);
        r.start_job("build", None);
        r.finish_job_failure("build", Duration::from_secs(2));
        // Both report_completion shapes (with and without an exit code).
        r.println("Job 'build' failed (exit code: 2)");
        r.println("Job 'build' failed");
        // Author fail_text and unrelated messages pass through as section
        // content — inside the gutter.
        r.println("see docs/build.md");
        let contents = term.contents();
        assert!(
            !contents.contains("Job 'build' failed"),
            "redundant runner line must be dropped: {contents}"
        );
        assert!(contents.contains("\u{2502}  see docs/build.md"));
    }

    #[test]
    fn live_bars_repad_when_a_wider_job_starts() {
        let (mut r, _term, _h) = harness(None, false);
        r.start_job("fmt", None);
        r.update_job_output("fmt", "running");
        let short = r.jobs.get("fmt").unwrap().bar.message();
        assert!(short.starts_with("fmt  "), "got: {short:?}");
        r.start_job("integration-tests", None);
        let repadded = r.jobs.get("fmt").unwrap().bar.message();
        assert!(
            repadded.starts_with(&format!("{:<17}  ", "fmt")),
            "existing bars re-pad to the new column: {repadded:?}"
        );
    }

    #[test]
    fn description_seeds_the_live_annotation_until_output_arrives() {
        let (mut r, _term, _h) = harness(None, false);
        r.start_job_with_description("db", Some("Prepare the database"), None);
        let seeded = r.jobs.get("db").unwrap().bar.message();
        assert!(
            seeded.contains("Prepare the database"),
            "description shows before output: {seeded:?}"
        );
        r.update_job_output("db", "applying migration 3");
        let live = r.jobs.get("db").unwrap().bar.message();
        assert!(live.contains("applying migration 3"), "got: {live:?}");
        assert!(!live.contains("Prepare the database"));
    }

    // ── verbose: the threaded log ─────────────────────────────────────────

    #[test]
    fn verbose_receipt_threads_the_log_under_the_row() {
        let (mut r, term, _h) = harness_with(verbose_config(), None, false);
        r.start_job_with_description("build", None, Some("cargo build"));
        r.update_job_output("build", "compiling daft");
        r.update_job_output("build", "finished dev profile");
        r.finish_job_success("build", Duration::from_millis(2100));
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{2713}  build  (2.1s)\n\
             \u{2502}  \u{2502}    \u{276f} cargo build\n\
             \u{2502}  \u{2502}    compiling daft\n\
             \u{2502}  \u{2502}    finished dev profile\n\
             \u{2502}  \u{2502}"
        );
    }

    #[test]
    fn verbose_anchor_carries_hook_key_and_version() {
        let (r, term, _h) = harness_with(verbose_config(), Some("post-create hooks"), false);
        r.print_header("worktree-post-create", Some("feat/x"));
        assert_eq!(
            term.contents(),
            format!(
                "\u{251c}\u{2500} post-create hooks  worktree-post-create \u{b7} daft v{}",
                crate::VERSION
            )
        );
    }

    #[test]
    fn succinct_anchor_stays_bare() {
        let (r, term, _h) = harness(Some("post-create hooks"), false);
        r.print_header("worktree-post-create", None);
        assert_eq!(term.contents(), "\u{251c}\u{2500} post-create hooks");
    }

    #[test]
    fn verbose_live_thread_opens_with_the_command_and_rolls_the_window() {
        let config = HookOutputConfig {
            verbose: true,
            tail_lines: 2,
            ..Default::default()
        };
        let (mut r, _term, _h) = harness_with(config, None, false);
        r.start_job_with_description("build", Some("Compile the project"), Some("cargo build"));
        {
            let state = r.jobs.get("build").unwrap();
            let cmd = state.cmd_bar.as_ref().expect("verbose opens a ❯ cmd bar");
            assert!(cmd.message().contains("\u{276f} cargo build"));
        }
        for i in 0..5 {
            r.update_job_output("build", &format!("line {i}"));
        }
        let state = r.jobs.get("build").unwrap();
        assert_eq!(
            state.tail_bars.len(),
            2,
            "live window caps at tailLines bars"
        );
        assert_eq!(state.tail_bars[0].message(), "line 3");
        assert_eq!(state.tail_bars[1].message(), "line 4");
        assert_eq!(state.output.len(), 5, "the receipt buffer is unwindowed");
        assert!(
            state.bar.message().contains("Compile the project"),
            "the thread carries liveness — the annotation keeps the description: {:?}",
            state.bar.message()
        );
    }

    #[test]
    fn verbose_failure_logs_inline_and_defers_only_the_exit_fact() {
        let (mut r, term, h) = harness_with(verbose_config(), None, false);
        r.start_job_with_description("build", None, Some("cargo build"));
        r.update_job_output("build", "error: lockfile out of date");
        r.finish_job_failure("build", Duration::from_millis(2900));
        // The runner always follows the failure with this line.
        r.println("Job 'build' failed (exit code: 1)");
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{2717}  build  (2.9s)\n\
             \u{2502}  \u{2502}    \u{276f} cargo build\n\
             \u{2502}  \u{2502}    error: lockfile out of date\n\
             \u{2502}  \u{2502}"
        );
        assert_eq!(
            deferred(&h),
            vec!["error: hook job 'build' failed (exit code: 1)".to_string()],
            "the log is inline — only the exit fact defers, never a dump"
        );
    }

    #[test]
    fn verbose_failure_without_exit_code_defers_the_bare_fact() {
        let (mut r, _term, h) = harness_with(verbose_config(), None, false);
        r.start_job("build", None);
        r.finish_job_failure("build", Duration::from_secs(2));
        r.println("Job 'build' failed");
        assert_eq!(
            deferred(&h),
            vec!["error: hook job 'build' failed".to_string()]
        );
    }

    #[test]
    fn verbose_success_log_recedes_grey_failure_log_keeps_default_ink() {
        let (mut r, _term, _h) = harness_with(verbose_config(), None, true);
        r.start_job("build", None);
        r.update_job_output("build", "some output");
        let state = r.jobs.get("build").unwrap();
        let success = r.compose_log(state, false);
        let failure = r.compose_log(state, true);
        assert!(
            success[0].contains(&format!("{GREY}some output{}", styles::RESET)),
            "a receipt recedes: {success:?}"
        );
        assert!(
            failure[0].ends_with("    some output"),
            "evidence keeps the default ink: {failure:?}"
        );
    }

    #[test]
    fn multiline_command_flattens_to_one_thread_line() {
        // Block-scalar `run:` commands carry newlines; a thread line must
        // stay a single line or the gutter tears.
        assert_eq!(
            command_line("echo one\necho two\nexit 7\n"),
            "echo one \u{2026}"
        );
        assert_eq!(command_line("cargo build"), "cargo build");
        assert_eq!(command_line("cargo build\n"), "cargo build");
        let (mut r, term, _h) = harness_with(verbose_config(), None, false);
        r.start_job_with_description("build", None, Some("echo one\nexit 7"));
        r.finish_job_success("build", Duration::from_millis(100));
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{2713}  build\n\
             \u{2502}  \u{2502}    \u{276f} echo one \u{2026}\n\
             \u{2502}  \u{2502}    (no output)\n\
             \u{2502}  \u{2502}"
        );
    }

    #[test]
    fn verbose_silent_job_marks_no_output() {
        let (mut r, term, _h) = harness_with(verbose_config(), None, false);
        r.start_job_with_description("build", None, Some("cargo build"));
        r.finish_job_success("build", Duration::from_millis(300));
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{2713}  build\n\
             \u{2502}  \u{2502}    \u{276f} cargo build\n\
             \u{2502}  \u{2502}    (no output)\n\
             \u{2502}  \u{2502}"
        );
    }

    #[test]
    fn quiet_verbose_suppresses_threads_but_not_the_exit_fact() {
        let config = HookOutputConfig {
            verbose: true,
            quiet: true,
            ..Default::default()
        };
        let (mut r, term, h) = harness_with(config, None, false);
        r.start_job_with_description("build", None, Some("cargo build"));
        assert!(
            r.jobs.get("build").unwrap().cmd_bar.is_none(),
            "quiet keeps the thread off the live region"
        );
        r.update_job_output("build", "secret output");
        assert!(r.jobs.get("build").unwrap().tail_bars.is_empty());
        r.finish_job_failure("build", Duration::from_secs(2));
        r.println("Job 'build' failed (exit code: 1)");
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{2717}  build  (2.0s)",
            "row only — no thread, no log"
        );
        assert_eq!(
            deferred(&h),
            vec!["error: hook job 'build' failed (exit code: 1)".to_string()],
            "the exit fact is daft's metadata, not hook output — quiet keeps it"
        );
    }

    #[test]
    fn verbose_closing_note_carries_the_phase_total() {
        let (mut r, term, _h) = harness_with(verbose_config(), None, false);
        r.start_job("fmt", None);
        r.finish_job_success("fmt", Duration::from_millis(300));
        r.print_summary(Duration::from_millis(3000));
        assert!(
            term.contents()
                .ends_with("\u{2502}  \u{2514}  all jobs in 3.0s"),
            "the section closes with its own rail end, got: {}",
            term.contents()
        );
    }

    #[test]
    fn closing_note_skips_empty_phases_and_succinct_mode() {
        let (r, term, _h) = harness_with(verbose_config(), None, false);
        r.print_summary(Duration::from_secs(3));
        assert_eq!(term.contents(), "", "no jobs — no note");
        let (mut r, term, _h) = harness(None, false);
        r.start_job("fmt", None);
        r.finish_job_success("fmt", Duration::from_millis(300));
        r.print_summary(Duration::from_secs(3));
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{2713}  fmt",
            "succinct never prints a summary note"
        );
    }

    #[test]
    fn verbose_condition_skips_stay_silent() {
        let (mut r, term, _h) = harness_with(verbose_config(), None, false);
        r.finish_job_skipped("lint", "skip: true", Duration::ZERO, false, None);
        assert_eq!(term.contents(), "");
    }

    #[test]
    fn silent_job_promotes_to_elapsed_and_output_unpromotes() {
        let config = HookOutputConfig {
            verbose: true,
            timer_delay_secs: 0,
            ..Default::default()
        };
        let (mut r, _term, _h) = harness_with(config, None, false);
        r.start_job_with_description("build", Some("Compile everything"), None);
        // The promoter runs on a detached ticker thread; poll rather than
        // sleep a fixed amount (same pattern as the block renderer's test).
        let deadline = std::time::Instant::now() + Duration::from_secs(2);
        while !r.timer_promoted("build") && std::time::Instant::now() < deadline {
            std::thread::sleep(Duration::from_millis(10));
        }
        assert!(
            r.timer_promoted("build"),
            "a silent job past timerDelay gains the elapsed counter"
        );
        let msg = r.jobs.get("build").unwrap().bar.message();
        assert!(
            msg.starts_with("build") && msg.contains('('),
            "the counter seats in the annotation slot: {msg:?}"
        );
        r.update_job_output("build", "first line");
        // A ticker iteration that raced past the flags settles on its next
        // wake (≤ 1s); poll for the restored annotation.
        let settled = |r: &RailHookRenderer| {
            let msg = r.jobs.get("build").unwrap().bar.message();
            !r.timer_promoted("build") && msg.contains("Compile everything") && !msg.contains('(')
        };
        let deadline = std::time::Instant::now() + Duration::from_secs(3);
        while !settled(&r) && std::time::Instant::now() < deadline {
            std::thread::sleep(Duration::from_millis(20));
        }
        assert!(
            settled(&r),
            "output retires the counter and the description returns: {:?}",
            r.jobs.get("build").unwrap().bar.message()
        );
    }

    #[test]
    fn succinct_never_promotes() {
        let config = HookOutputConfig {
            timer_delay_secs: 0,
            ..Default::default()
        };
        let (mut r, _term, _h) = harness_with(config, None, false);
        r.start_job("build", None);
        std::thread::sleep(Duration::from_millis(100));
        assert!(
            !r.timer_promoted("build"),
            "promotion is a verbose affordance"
        );
    }
}
