//! Succinct rail-native renderer for hook jobs (#651).
//!
//! The default hook appearance on the rail: one receipt row per job in the
//! rail's own grammar, tucked into the rail gutter (`│  ✓  <job>`) under a
//! `├─ <section>` anchor — no banner, no output dumps, no summary. The full
//! block (`hook_progress::HookProgressRenderer`) remains the verbose
//! appearance (`-v` / `daft.hooks.output.verbose`).
//!
//! Live shape: each running job is a spinner bar whose annotation is the
//! job's latest output line, dim, updating in place — one line of liveness
//! per job instead of the block's rolling tail. Receipts persist in
//! completion order (same as the block). A failed job's captured output is
//! not dumped inline; it rides [`TimelineHandle::defer_after_footer`] and
//! lands below the rail footer, where the rail already puts failure detail.

use super::render::{self, RowFace};
use super::{HookEmbed, TimelineHandle};
use crate::output::hook_progress::{JobOutcome, JobResultEntry};
use crate::output::palette::{DARK_GREY, GREY};
use crate::settings::HookOutputConfig;
use crate::styles;
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use std::collections::{HashMap, HashSet};
use std::time::Duration;

/// A per-job skip reason generated by the condition machinery (`skip:` /
/// `only:` in the job's YAML). The config working as designed is not receipt
/// material — these resolve silently, like the carry row on a clean tree.
/// Everything else that reaches a skip (`--skip-hooks` exclusions,
/// dependency failures) renders the yellow attention row.
///
/// Defensive on the per-job path: today condition skips never reach the
/// presenter at all (`yaml_jobs_to_specs` filters them before execution and
/// only the job store records them); this guards the succinct rail if that
/// ever changes. Load-bearing on the hook level: `resolve_hook_step` uses it
/// to vanish a whole phase skipped by `hook_def.skip`/`only`.
pub(super) fn is_condition_skip(reason: &str) -> bool {
    reason.starts_with("skip: ") || reason.starts_with("only: ")
}

struct JobState {
    bar: ProgressBar,
    /// Everything the job printed, buffered for the failure dump.
    output: Vec<String>,
    /// The live annotation: latest output line, seeded from the job's
    /// description. Kept unpainted; painted at composition.
    annotation: Option<String>,
}

pub struct RailHookRenderer {
    mp: MultiProgress,
    anchor: ProgressBar,
    handle: TimelineHandle,
    use_color: bool,
    quiet: bool,
    section_label: Option<String>,
    job_style: ProgressStyle,
    jobs: HashMap<String, JobState>,
    /// Jobs already resolved `✗` — used to drop the runner's redundant
    /// `Job '<name>' failed…` message (the row and the deferred dump carry
    /// the fact).
    failed: HashSet<String>,
    finished: Vec<JobResultEntry>,
    /// Running max of started job names; live bars re-pad when it grows.
    name_width: usize,
}

impl RailHookRenderer {
    pub fn new(embed: HookEmbed, handle: TimelineHandle, config: &HookOutputConfig) -> Self {
        // `wide_msg`, not `msg`: hook output is arbitrary — a line wider
        // than the terminal must truncate, or it wraps and desyncs
        // indicatif's line accounting. The rail gutter rides the template —
        // the spinner glyph lives there, so the message can't provide it.
        let base = if embed.use_color {
            "{spinner:.cyan}  {wide_msg}"
        } else {
            "{spinner}  {wide_msg}"
        };
        let job_style = ProgressStyle::with_template(&render::gutter(base, embed.use_color))
            .expect("job template is valid")
            .tick_chars(super::region::TICK_CHARS);
        Self {
            mp: embed.mp,
            anchor: embed.anchor,
            handle,
            use_color: embed.use_color,
            quiet: config.quiet,
            section_label: embed.section_label,
            job_style,
            jobs: HashMap::new(),
            failed: HashSet::new(),
            finished: Vec::new(),
            name_width: 0,
        }
    }

    /// The `├─ <section>` anchor. The consumed rail row's label names the
    /// section; gate embeds (pre-push under an active Push row) fall back to
    /// the phase name.
    pub fn print_header(&self, hook_name: &str, _target: Option<&str>) {
        let label = match &self.section_label {
            Some(label) => label.clone(),
            None => format!("{hook_name} hooks"),
        };
        self.mp.println(render::group(&label, self.use_color)).ok();
    }

    pub fn start_job(&mut self, name: &str, command_preview: Option<&str>) {
        self.start_job_with_description(name, None, command_preview);
    }

    pub fn start_job_with_description(
        &mut self,
        name: &str,
        description: Option<&str>,
        _command_preview: Option<&str>,
    ) {
        let bar = self
            .mp
            .insert_before(&self.anchor, ProgressBar::new_spinner());
        bar.set_style(self.job_style.clone());
        let state = JobState {
            bar,
            output: Vec::new(),
            annotation: description.map(str::to_string),
        };
        self.jobs.insert(name.to_string(), state);
        self.grow_width_to(name.chars().count());
        self.refresh_bar(name);
        if let Some(state) = self.jobs.get(name) {
            state.bar.enable_steady_tick(Duration::from_millis(80));
        }
    }

    pub fn update_job_output(&mut self, name: &str, line: &str) {
        let Some(state) = self.jobs.get_mut(name) else {
            return;
        };
        state.output.push(line.to_string());
        if self.quiet {
            return;
        }
        state.annotation = Some(line.trim_end().to_string());
        self.refresh_bar(name);
    }

    pub fn finish_job_success(&mut self, name: &str, duration: Duration) {
        self.remove_bar(name);
        self.persist_receipt(render::final_row(
            &RowFace::Done {
                duration: Some(duration),
            },
            name,
            None,
            self.name_width,
            self.use_color,
        ));
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Success,
            duration,
        });
    }

    pub fn finish_job_failure(&mut self, name: &str, duration: Duration) {
        let output = self.remove_bar(name);
        self.persist_receipt(render::final_row(
            &RowFace::Failed,
            name,
            self.duration_annotation(duration).as_deref(),
            self.name_width,
            self.use_color,
        ));
        self.failed.insert(name.to_string());
        // The captured output lands below the rail footer — the rail's
        // errors-after pattern — not torn through the live bars. `quiet`
        // keeps its "suppress hook stdout/stderr" contract.
        if !self.quiet && !output.is_empty() {
            let head = if self.use_color {
                format!(
                    "{}error:{} hook job '{name}' failed:",
                    styles::RED,
                    styles::RESET
                )
            } else {
                format!("error: hook job '{name}' failed:")
            };
            let mut lines = vec![head];
            lines.extend(output.iter().map(|l| format!("  {l}")));
            self.handle.defer_after_footer(lines);
        }
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Failed,
            duration,
        });
    }

    pub fn finish_job_skipped(
        &mut self,
        name: &str,
        reason: &str,
        duration: Duration,
        show_duration: bool,
        _command_preview: Option<&str>,
    ) {
        self.remove_bar(name);
        if !is_condition_skip(reason) {
            self.persist_receipt(render::final_row(
                &RowFace::SkippedAttention,
                name,
                Some(&format!("skipped \u{2014} {reason}")),
                self.name_width,
                self.use_color,
            ));
        }
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Skipped {
                reason: reason.to_string(),
                show_duration,
            },
            duration,
        });
    }

    /// Hooks have no cancellation path today (only `daft exec` cancels, and
    /// it always runs the block renderer) — defensive parity.
    pub fn finish_job_cancelled(&mut self, name: &str, duration: Duration) {
        self.remove_bar(name);
        self.persist_receipt(render::final_row(
            &RowFace::Failed,
            name,
            Some("cancelled"),
            self.name_width,
            self.use_color,
        ));
        self.failed.insert(name.to_string());
        self.finished.push(JobResultEntry {
            name: name.to_string(),
            outcome: JobOutcome::Failed,
            duration,
        });
    }

    /// `↻ <name>  background` — the dispatch receipt; the job itself runs
    /// under the coordinator, visible via `daft hooks jobs`.
    pub fn show_background_job(&mut self, name: &str, _description: Option<&str>) {
        self.grow_width_to(name.chars().count());
        self.persist_receipt(render::final_row(
            &RowFace::Background,
            name,
            None,
            self.name_width,
            self.use_color,
        ));
    }

    pub fn push_finished_job(&mut self, entry: JobResultEntry) {
        self.finished.push(entry);
    }

    /// No summary in succinct mode: every job already has exactly one
    /// receipt row.
    pub fn print_summary(&self, _total_duration: Duration) {}

    pub fn take_finished_jobs(&mut self) -> Vec<JobResultEntry> {
        std::mem::take(&mut self.finished)
    }

    pub fn println(&self, msg: &str) {
        // The runner follows every on_job_failure with a
        // `Job '<name>' failed…` message (runner::report_completion) — on
        // the rail that is redundant with the `✗` row and the deferred
        // dump. Author-supplied `fail_text` and other messages (e.g. the
        // `⟳ N background jobs running` notice) pass through as section
        // content, each line tucked into the gutter.
        let redundant = self
            .failed
            .iter()
            .any(|name| msg.starts_with(&format!("Job '{name}' failed")));
        if !redundant {
            for line in msg.lines() {
                self.mp.println(render::gutter(line, self.use_color)).ok();
            }
        }
    }

    /// Persist a receipt row inside the rail gutter — every job row is
    /// section content under the `├─` anchor.
    fn persist_receipt(&self, row: String) {
        self.mp.println(render::gutter(&row, self.use_color)).ok();
    }

    /// Bump the alignment column and re-pad every live bar when it grows.
    fn grow_width_to(&mut self, width: usize) {
        if width <= self.name_width {
            return;
        }
        self.name_width = width;
        let names: Vec<String> = self.jobs.keys().cloned().collect();
        for name in names {
            self.refresh_bar(&name);
        }
    }

    /// Recompose a live bar's message from its stored annotation.
    fn refresh_bar(&self, name: &str) {
        let Some(state) = self.jobs.get(name) else {
            return;
        };
        let msg = match state.annotation.as_deref().filter(|a| !a.is_empty()) {
            Some(a) => format!(
                "{name:<width$}  {}",
                render::paint(DARK_GREY, a, self.use_color),
                width = self.name_width
            ),
            None => name.to_string(),
        };
        state.bar.set_message(msg);
    }

    /// Remove the job's live bar (receipts replace it via `mp.println` — the
    /// atomic swap; never `finish_and_clear`, per the zombie-line lesson).
    /// Returns the buffered output. Jobs that never started (skips) have no
    /// state; that's fine.
    fn remove_bar(&mut self, name: &str) -> Vec<String> {
        match self.jobs.remove(name) {
            Some(state) => {
                state.bar.disable_steady_tick();
                self.mp.remove(&state.bar);
                state.output
            }
            None => Vec::new(),
        }
    }

    /// The rail's duration vocabulary for faces that don't carry their own:
    /// dim, parenthesized, only at ≥ 1s.
    fn duration_annotation(&self, duration: Duration) -> Option<String> {
        (duration >= render::DURATION_THRESHOLD).then(|| {
            render::paint(
                GREY,
                &format!(
                    "({})",
                    crate::output::hook_progress::format_duration(duration)
                ),
                self.use_color,
            )
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::timeline::{Timeline, TimelineMode};
    use indicatif::{InMemoryTerm, ProgressDrawTarget};

    fn harness(
        section_label: Option<&str>,
        quiet: bool,
    ) -> (RailHookRenderer, InMemoryTerm, TimelineHandle) {
        let term = InMemoryTerm::new(40, 120);
        let mp =
            MultiProgress::with_draw_target(ProgressDrawTarget::term_like(Box::new(term.clone())));
        let anchor = mp.add(ProgressBar::new_spinner());
        anchor.set_style(ProgressStyle::with_template("{msg}").unwrap());
        let tl = Timeline::new(TimelineMode::Interactive { color: false }, false, "t");
        let handle = tl.handle();
        let embed = HookEmbed {
            mp,
            anchor,
            use_color: false,
            section_label: section_label.map(String::from),
        };
        let config = HookOutputConfig {
            quiet,
            ..Default::default()
        };
        (
            RailHookRenderer::new(embed, handle.clone(), &config),
            term,
            handle,
        )
    }

    fn deferred(handle: &TimelineHandle) -> Vec<String> {
        handle.inner.lock().unwrap().deferred_after_footer.clone()
    }

    #[test]
    fn success_receipt_uses_rail_grammar() {
        let (mut r, term, _h) = harness(Some("post-create hooks"), false);
        r.print_header("worktree-post-create", Some("feat/x"));
        r.start_job_with_description("build", None, Some("cargo build"));
        r.update_job_output("build", "compiling…");
        r.finish_job_success("build", Duration::from_millis(2100));
        assert_eq!(
            term.contents(),
            "\u{251c}\u{2500} post-create hooks\n\u{2502}  \u{2713}  build  (2.1s)"
        );
        let jobs = r.take_finished_jobs();
        assert_eq!(jobs.len(), 1);
        assert!(matches!(jobs[0].outcome, JobOutcome::Success));
    }

    #[test]
    fn subsecond_success_hides_duration() {
        let (mut r, term, _h) = harness(None, false);
        r.start_job("fmt", None);
        r.finish_job_success("fmt", Duration::from_millis(300));
        assert_eq!(term.contents(), "\u{2502}  \u{2713}  fmt");
    }

    #[test]
    fn gate_embed_derives_anchor_from_phase_name() {
        let (r, term, _h) = harness(None, false);
        r.print_header("pre-push", Some("feat/x"));
        assert_eq!(term.contents(), "\u{251c}\u{2500} pre-push hooks");
    }

    #[test]
    fn failure_row_and_dump_deferred_after_footer() {
        let (mut r, term, h) = harness(None, false);
        r.start_job("build", None);
        r.update_job_output("build", "error: lockfile out of date");
        r.update_job_output("build", "note: run bun install");
        r.finish_job_failure("build", Duration::from_millis(2900));
        assert_eq!(term.contents(), "\u{2502}  \u{2717}  build  (2.9s)");
        assert_eq!(
            deferred(&h),
            vec![
                "error: hook job 'build' failed:".to_string(),
                "  error: lockfile out of date".to_string(),
                "  note: run bun install".to_string(),
            ]
        );
    }

    #[test]
    fn failure_without_output_defers_nothing() {
        let (mut r, _term, h) = harness(None, false);
        r.start_job("build", None);
        r.finish_job_failure("build", Duration::from_secs(1));
        assert!(deferred(&h).is_empty());
    }

    #[test]
    fn quiet_suppresses_annotation_and_dump() {
        let (mut r, term, h) = harness(None, true);
        r.start_job("build", None);
        r.update_job_output("build", "secret output");
        assert!(
            !term.contents().contains("secret output"),
            "quiet must keep hook output off the live bar: {}",
            term.contents()
        );
        r.finish_job_failure("build", Duration::from_secs(2));
        assert!(deferred(&h).is_empty(), "quiet suppresses the dump");
    }

    #[test]
    fn requested_and_dependency_skips_render_yellow() {
        // Pins every reason the executor can send through on_job_skipped:
        // SkipCause::reason() (job_adapter) and the runner's dep-failure
        // family. All are attention-worthy on the rail.
        let reasons = [
            "requested (--skip-hooks)",
            "depends on install (skipped)",
            "dependency failed",
            "previous job failed",
            "foreground dependency failed",
        ];
        for reason in reasons {
            let (mut r, term, _h) = harness(None, false);
            r.finish_job_skipped("lint", reason, Duration::ZERO, false, None);
            assert_eq!(
                term.contents(),
                format!("\u{2502}  \u{2193}  lint  skipped \u{2014} {reason}"),
                "reason {reason:?} must render the attention row"
            );
        }
    }

    #[test]
    fn condition_skips_resolve_silently() {
        // Defensive: condition skips are filtered before the presenter
        // today; if they ever arrive, the config working as designed must
        // not become receipt noise.
        for reason in ["skip: true", "only: env $CI is not set"] {
            let (mut r, term, _h) = harness(None, false);
            r.finish_job_skipped("lint", reason, Duration::ZERO, false, None);
            assert_eq!(term.contents(), "", "reason {reason:?} must be silent");
            let jobs = r.take_finished_jobs();
            assert!(
                matches!(&jobs[0].outcome, JobOutcome::Skipped { .. }),
                "silent skips still record their outcome"
            );
        }
    }

    #[test]
    fn background_row_persists_with_fixed_annotation() {
        let (mut r, term, _h) = harness(None, false);
        r.show_background_job("check-todos", Some("scan for TODOs"));
        r.push_finished_job(JobResultEntry {
            name: "check-todos".to_string(),
            outcome: JobOutcome::Background { description: None },
            duration: Duration::ZERO,
        });
        assert_eq!(
            term.contents(),
            "\u{2502}  \u{21bb}  check-todos  background"
        );
        assert!(matches!(
            r.take_finished_jobs()[0].outcome,
            JobOutcome::Background { .. }
        ));
    }

    #[test]
    fn runner_failure_message_is_suppressed_for_failed_jobs() {
        let (mut r, term, _h) = harness(None, false);
        r.start_job("build", None);
        r.finish_job_failure("build", Duration::from_secs(2));
        // Both report_completion shapes (with and without an exit code).
        r.println("Job 'build' failed (exit code: 2)");
        r.println("Job 'build' failed");
        // Author fail_text and unrelated messages pass through as section
        // content — inside the gutter.
        r.println("see docs/build.md");
        let contents = term.contents();
        assert!(
            !contents.contains("Job 'build' failed"),
            "redundant runner line must be dropped: {contents}"
        );
        assert!(contents.contains("\u{2502}  see docs/build.md"));
    }

    #[test]
    fn live_bars_repad_when_a_wider_job_starts() {
        let (mut r, _term, _h) = harness(None, false);
        r.start_job("fmt", None);
        r.update_job_output("fmt", "running");
        let short = r.jobs.get("fmt").unwrap().bar.message();
        assert!(short.starts_with("fmt  "), "got: {short:?}");
        r.start_job("integration-tests", None);
        let repadded = r.jobs.get("fmt").unwrap().bar.message();
        assert!(
            repadded.starts_with(&format!("{:<17}  ", "fmt")),
            "existing bars re-pad to the new column: {repadded:?}"
        );
    }

    #[test]
    fn description_seeds_the_live_annotation_until_output_arrives() {
        let (mut r, _term, _h) = harness(None, false);
        r.start_job_with_description("db", Some("Prepare the database"), None);
        let seeded = r.jobs.get("db").unwrap().bar.message();
        assert!(
            seeded.contains("Prepare the database"),
            "description shows before output: {seeded:?}"
        );
        r.update_job_output("db", "applying migration 3");
        let live = r.jobs.get("db").unwrap().bar.message();
        assert!(live.contains("applying migration 3"), "got: {live:?}");
        assert!(!live.contains("Prepare the database"));
    }
}
