#!/bin/sh
set -e

case "$1" in
    configure)
        for cmd in git-worktree-clone git-worktree-init git-worktree-checkout \
                   git-worktree-checkout-branch git-worktree-prune git-worktree-carry \
                   git-worktree-fetch git-worktree-flow-adopt git-worktree-flow-eject \
                   git-sync git-daft daft-remove daft-rename; do
            ln -sf daft "/usr/bin/$cmd"
        done
        ;;
esac

#DEBHELPER#
