#!/usr/bin/env bash
# Guard: .github/workflows/release.yml is generated by `dist generate`, which
# drops the manually maintained DAFT_BUILD_RELEASE env block when re-run.
# Without that block, release binaries are built with the daft_dev_build cfg
# and honor the DAFT_{CONFIG,DATA,STATE}_DIR redirects (#669). Fail CI until
# the block is restored.
set -euo pipefail

workflow=".github/workflows/release.yml"

if ! grep -qE '^\s*DAFT_BUILD_RELEASE:' "$workflow"; then
  {
    echo "error: $workflow does not set DAFT_BUILD_RELEASE."
    echo "Release binaries would be built as dev builds (daft_dev_build cfg)"
    echo "and honor DAFT_*_DIR redirects. Restore the manually maintained env"
    echo "block near the top of the workflow — 'dist generate' removes it."
    echo "See #669."
  } >&2
  exit 1
fi

echo "ok: $workflow sets DAFT_BUILD_RELEASE"
